name: inception

services:
	webserver:
		command: echo "I'm running ${COMPOSE_PROJECT_NAME}/webserver"
	contentserver:
		command: echo "I'm running ${COMPOSE_PROJECT_NAME}/contentserver"
	dbserver:
		command: echo "I'm running ${COMPOSE_PROJECT_NAME}/webserver"
	
