name: inception
include:
  - ./requirements/dbserver/docker-compose-dbserver.yml
  - ./requirements/webserver/docker-compose-webserver.yml
  - ./requirements/contentserver/docker-compose-contentserver.yml
  - ./requirements/adminer/docker-compose-adminer.yml


networks:
  inception_net:
    name: thenet
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/28  # Define the IP range

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: "/data/db"
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: "/data/wp"
      o: bind

secrets:
  dbserver_root_password:
    file: ../../secrets/dbserver_root_password.txt
  dbserver_msql_password:
    file: ../../secrets/dbserver_msql_password.txt
  contentserver_root_password:
    file: ../../secrets/contentserver_root_password.txt
  contentserver_user_password:
    file: ../../secrets/contentserver_user_password.txt


#secrets:
#  dbserver_root_password:
#    external: true
#  dbserver_msql_password:
#    external: true
#  contentserver_root_password:
#    external: true
#  contentserver_user_password:
#    external: true



