services:
  adminerserver:
    image: adminerserver
    build:
      context: ../adminer
      dockerfile: dockerfile_adminer
    networks:
      inception_net:
        ipv4_address: 192.168.1.8  # Fixed IP for adminer
    env_file:
      - ../../.env
    secrets:
      - dbserver_msql_password
    depends_on:
      - dbserver
    restart: always
    ports:
      - "8080:80"  # Optional: expose Adminer to localhost:8080
    logging:
      driver: "json-file"
      options:
        max-size: "30k"
        max-file: "3"