FROM alpine:3.21.3
LABEL org.label-schema.schema-version = "1.0"
LABEL org.label-schema.maintainer="Luis Miguel Casado Díaz <luicasad@student.42barcelona.com>"
LABEL org.label-schema.version="11.4.5"
LABEL org.label-schema.description="A Docker image running MariaDB client on Alpine Linux."
LABEL org.label-schema.url="[https://github.com/luismiguelcasadodiaz/inception]"
LABEL org. label-schema.date="May 2025"

RUN apk add --no-cache mariadb-client 
RUN adduser mysql

COPY docker-entrypoint.sh /usr/local/sbin/docker-entrypoint.sh

RUN chmod +x /usr/local/sbin/docker-entrypoint.sh

# only to test server
ENTRYPOINT ["/usr/local/sbin/docker-entrypoint.sh"]

# Example default arguments
