services:
  client:
    command: ["/bin/sh", "-c", "echo \"running client\"; exec /bin/sh"]

    image: client # EL nombre de la imagen debe coincidir con el nombre del servicio
    depends_on:
      dbserver:
        condition: service_healthy  # Ensures database server is actually ready
    networks:
      inception_net:
        ipv4_address: 192.168.1.14  # Fixed IP
    restart: always
    build:
      context: ../client
      dockerfile: dockerfile_client
      
    # --- Secrets Configuration ---      
    secrets:
      - dbserver_msql_password
    environment:
      DBSERVER_MSQL_PASSWORD_FILE: /run/secrets/dbserver_msql_password

    # --- Logging Configuration ---
    logging:
      driver: "json-file" # Use json-file for easier access if you need to debug raw logs
      options:
        max-size: "25600" # Keep each log file up to 25600 Bytes
        max-file: "3"   # Keep the 3 most recent log files