services:
  dbserver:
    command: echo "I'm running ${COMPOSE_PROJECT_NAME}/webserver"
    container_name: dbserver
    image: dbserver # EL nombre de la imagen debe coincidir con el nombre del servicio
    networks:
      inception_net:
        ipv4_address: 192.168.1.2  # Fixed IP
        aliases:
          - in_net
    restart: always
    build:
      context: ../dbserver
      dockerfile: dockerfile_dbserver
    #- ./db_data:/var/lib/mysql  # Maps host folder ./db_data to container dbserver  /var/lib/mysql directory
    volumes:
      - /home/luicasad/data/db:/var/lib/mysql  # Maps host folder ./db_data to container dbserver  /var/lib/mysql directory
    ports:
      - "3306:3306"
    secrets:
      - dbserver_root_password
      - dbserver_msql_password
    env_file:
      - ../../.env
    #environment:
      #DBSERVER_ROOT_PASSWORD_FILE: /run/secrets/dbserver_root_password
      #DBSERVER_MSQL_PASSWORD_FILE: /run/secrets/dbserver_msql_password
    # --- Logging Configuration ---
    logging:
      driver: "json-file" # Use json-file for easier access if you need to debug raw logs
      options:
        max-size: "30k" # Keep each log file up to 30KB
        max-file: "3"   # Keep the 3 most recent log files      