FROM alpine:3.21.3
LABEL org.label-schema.schema-version = "1.0"
LABEL org.label-schema.maintainer="Luis Miguel Casado Díaz <luicasad@student.42barcelona.com>"
LABEL org.label-schema.version="11.4.5"
LABEL org.label-schema.description="A Docker image running MariaDB server on Alpine Linux."
LABEL org.label-schema.url="[https://github.com/luismiguelcasadodiaz/inception]"
LABEL org. label-schema.date="May 2025"

RUN apk add --no-cache mariadb mariadb-client 

# recreate mysql folder with appropiate ownerrship
RUN set -ex; \
    rm -rf /var/lib/mysql; \
    mkdir -p /var/lib/mysql /var/run/mysql; \
    chown -R mysql:mysql /var/lib/mysql /var/run/mysql; \
    chmod 777 /var/run/mysql

VOLUME /var/lib/mysql

COPY docker-entrypoint.sh /usr/local/sbin/docker-entrypoint.sh
COPY healthcheck.sh /usr/local/sbin/healthcheck.sh

RUN chmod +x /usr/local/sbin/docker-entrypoint.sh ; \
    chmod +x /usr/local/sbin/healthcheck.sh ; \
    sed -i -e '/^skip-networking/ s/^skip-networking/#skip-networking/' /etc/my.cnf.d/mariadb-server.cnf

EXPOSE 3306

ENTRYPOINT ["/usr/local/sbin/docker-entrypoint.sh"]

#HEALTHCHECK --interval=10s --timeout=5s --retries=3 CMD mariadb-admin ping -u mysql --password="${DBSERVER_MSQL_PASSWORD}"-h localhost || exit 1
#  Dockerfile does not acces secrets, only .env defined variables. These is the reason to create a healthycheck script.
HEALTHCHECK --interval=10s --timeout=5s --retries=5 CMD /usr/local/sbin/healthcheck.sh || exit 1



# -rw-r--r--    1 root     root      475.6K May  8 08:36 APKINDEX.36c0efc6.tar.gz
# -rw-r--r--    1 root     root        1.9M May  8 08:36 APKINDEX.e33e93f4.tar.gz

# dbserver        latest    dcefd9c99bd4      237MB RUN apk add --no-cache mariadb mariadb-client 
# dbserver        latest    2eeab44f96e8      198MB RUN apk add --no-cache mariadb
