services:
  dbserver:
    command: echo "I'm running ${COMPOSE_PROJECT_NAME}/webserver"
    image: dbserver # EL nombre de la imagen debe coincidir con el nombre del servicio
    build:
      context: ../dbserver
      dockerfile: dockerfile_dbserver
    volumes:
      - ../dbserver/db_data:/data  # Maps host folder to MariaDB data directory
    ports:
      - "3306:3306"