services:
  contentserver:
    #command: echo "I'm running ${COMPOSE_PROJECT_NAME}/contentserver"
    image: contentserver # EL nombre de la imagen debe coincidir con el nombre del servicio
    networks:
      inception_net:
        ipv4_address: 192.168.1.3  # Fixed IP
    restart: always
    ports:
      - "9000:9000"
    build:
      context: ../contentserver
      dockerfile: dockerfile_contentserver
    volumes:
      - ./wp_data:/www  # Maps host folder to MariaDB data directory
    depends_on:
      dbserver:
        condition: service_healthy  # Ensures database server is actually ready
    env_file:
      - ../../.env
    secrets:
      - contentserver_root_password
      - contentserver_user_password
    #environment:
    #  CONTENTSERVER_ROOT_PASSWORD_FILE: /run/secrets/contentserver_root_password
    #  CONTENTSERVER_USER_PASSWORD_FILE: /run/secrets/contentserver_user_password
    # --- Logging Configuration ---
    logging:
      driver: "json-file" # Use json-file for easier access if you need to debug raw logs
      options:
        max-size: "3m" # Keep each log file up to 3MB
        max-file: "3"   # Keep the 3 most recent log files
