services:
  contentserver:
    command: echo "I'm running ${COMPOSE_PROJECT_NAME}/contentserver"
    image: contentserver # EL nombre de la imagen debe coincidir con el nombre del servicio
    restart: always
    build:
      context: ../contentserver
      dockerfile: dockerfile_contentserver
    depends_on:
      dbserver:
        condition: service_healthy  # Ensures database server is actually ready
    secrets:
      - contentserver_root_password
      - contentserver_user_password
    environment:
      CONTENTSERVER_ROOT_PASSWORD_FILE: /run/secrets/contentserver_root_password
      CONTENTSERVER_USER_PASSWORD_FILE: /run/secrets/contentserver_user_password