services:
  contentserver:
    #command: echo "I'm running ${COMPOSE_PROJECT_NAME}/contentserver"
    image: contentserver # EL nombre de la imagen debe coincidir con el nombre del servicio
    networks:
      inception_net:
        ipv4_address: 192.168.1.3  # Fixed IP
    restart: always
    ports:
      - "9000:9000"
    build:
      context: ../contentserver
      dockerfile: dockerfile_contentserver
    volumes:
      - ./wp_data:/www  # Maps host folder to container contentserver /www directory
    depends_on:
      dbserver:
        condition: service_healthy  # Ensures database server is actually ready
    env_file:
      - ../../.env
    secrets:
      - contentserver_root_password
      - contentserver_user_password
      - dbserver_msql_password
    # Specify the target (inside container path), uid, and gid
    deploy: # This applies to swarm mode, but similar concepts for simple compose
      secrets:
        - source: dbserver_msql_password
          target: /run/secrets/dbserver_msql_password
          uid: '0' # root
          gid: '101' # Or whatever GID your 'nginx' user uses.
                      # You need to find the GID of the 'nginx' group inside inception-contentserver-1.
                      # To find it: docker exec inception-contentserver-1 id -g nginx
                      # Common Nginx/PHP-FPM image GIDs are 33, 82, or 1001.
          mode: 0440 # Read-only for owner (root) and group (nginx), no access for others.
                     # This is more secure than 0770 you had.
    #environment:
    #  CONTENTSERVER_ROOT_PASSWORD_FILE: /run/secrets/contentserver_root_password
    #  CONTENTSERVER_USER_PASSWORD_FILE: /run/secrets/contentserver_user_password
    # --- Logging Configuration ---
    logging:
      driver: "json-file" # Use json-file for easier access if you need to debug raw logs
      options:
        max-size: "3m" # Keep each log file up to 3MB
        max-file: "3"   # Keep the 3 most recent log files
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "9000"]
      interval: 10s
      timeout: 3s
      retries: 5
