services:

  webserver:
    command: echo "I'm running ${COMPOSE_PROJECT_NAME}/webserver"
    image: webserver # EL nombre de la imagen debe coincidir con el nombre del servicio
    networks:
      inception_net:
        ipv4_address: 192.168.1.4  # Fixed IP
    restart: always
    build:
      context: ../webserver
      dockerfile: dockerfile_webserver
    ports:
      - "8080:80"