services:

  webserver:
    command: echo "I'm running ${COMPOSE_PROJECT_NAME}/webserver"
    image: webserver # EL nombre de la imagen debe coincidir con el nombre del servicio
    depends_on:
      dbserver:
        condition: service_healthy  # Ensures database server is actually ready
    networks:
      inception_net:
        ipv4_address: 192.168.1.4  # Fixed IP
    restart: always
    build:
      context: ../webserver
      dockerfile: dockerfile_webserver
    ports:
      - "443:443"
    # --- Logging Configuration ---
    logging:
      driver: "json-file" # Use json-file for easier access if you need to debug raw logs
      options:
        max-size: "3m" # Keep each log file up to 50MB
        max-file: "3"   # Keep the 5 most recent log files