FROM alpine:3.21.3
RUN apk add nginx
COPY webserver_setup.sh /webserver_setup.sh
RUN chmod +x /webserver_setup.sh && /webserver_setup.sh

COPY html/index.html /www/index.html
COPY html/bad_request_ssl.html /www/bad_request_ssl.html
COPY html/page_not_found.html /www/page_not_found.html
COPY nginx.conf /etc/nginx/nginx.conf

# THESE LINES COPY CERTIFICATES ......
RUN mkdir -p /etc/nginx/ssl # Create a directory inside the container for the certs
COPY ../data/certs/nginx.crt /etc/nginx/ssl/nginx.crt
COPY ../data/certs/nginx.key /etc/nginx/ssl/nginx.key
# ---------------------------------------------

EXPOSE 443
CMD ["/usr/sbin/nginx", "-c", "/etc/nginx/nginx.conf"]
