FROM alpine:3.21.3
RUN apk add nginx


# Change UID/GID of the mysql user to avoid conflicts with host users
# above apk add created mysql UID(100) GID(101)
# There is a collision with Host user Klogd
# Change UID in /etc/passwd
RUN sed -i 's/^nginx:x:[0-9]*:[0-9]*/nginx:x:1000:1000/' /etc/passwd

# Change GID in /etc/group
RUN sed -i 's/^nginx:x:[0-9]*/nginx:x:1000/' /etc/group

##COPY webserver_setup.sh /webserver_setup.sh
##RUN chmod +x /webserver_setup.sh && /webserver_setup.sh

#COPY html/index.html /www/index.html
COPY html/bad_request_ssl.html /www/bad_request_ssl.html
COPY html/page_not_found.html /www/page_not_found.html
COPY nginx.conf /etc/nginx/nginx.conf

# THESE LINES COPY CERTIFICATES ......
RUN mkdir -p /etc/nginx/ssl # Create a directory inside the container for the certs

# Makefile moved the at-boot-time-created certificates to this folder
# that makes certificates visible to Dockerfile
COPY nginx.crt /etc/nginx/ssl/nginx.crt
COPY nginx.key /etc/nginx/ssl/nginx.key
# ---------------------------------------------

EXPOSE 443
CMD ["/usr/sbin/nginx", "-c", "/etc/nginx/nginx.conf"]
